const PREFIX = '[waveform-playlist] ';

/** Injectable for tests — production uses native dynamic import. */
export type WamModuleImport = (url: string) => Promise<unknown>;

/** Structural view of a WAM plugin's descriptor (subset we validate/expose). */
export interface WamPluginDescriptor {
  name: string;
  vendor?: string;
  version?: string;
  apiVersion: string;
  hasAudioInput: boolean;
  hasAudioOutput: boolean;
  thumbnail?: string;
  description?: string;
}

/** Structural view of a WamNode — the plugin's AudioNode plus the WAM API surface. */
export interface WamPluginAudioNode extends AudioNode {
  destroy(): void;
  getState(): Promise<unknown>;
  setState(state: unknown): Promise<void>;
  getParameterInfo(...parameterIds: string[]): Promise<unknown>;
  setParameterValues?(
    values: Record<string, { id: string; value: number; normalized: boolean }>
  ): Promise<void>;
  scheduleEvents?(...events: Array<{ type: string; time: number; data?: unknown }>): void;
}

interface WamModuleLike {
  descriptor: WamPluginDescriptor;
  audioNode: WamPluginAudioNode;
  // GUI lifecycle lives on the WebAudioModule itself, NOT the audioNode.
  createGui?(): Promise<HTMLElement>;
  destroyGui?(gui: HTMLElement): void;
}

/** The module's default export: a WebAudioModule class (or object) with a createInstance factory. */
export interface WamFactory {
  createInstance(hostGroupId: string, audioContext: BaseAudioContext): Promise<WamModuleLike>;
}

/** A loaded, validated, live plugin wrapped for chain insertion. Headless — GUI handling is separate. */
export interface WamPluginInstance {
  /** Module URL for url-loaded plugins. Absent for factory-created instances
   *  (e.g. in-browser Faust compiles), which cannot be re-loaded from a URL. */
  url?: string;
  descriptor: WamPluginDescriptor;
  audioNode: WamPluginAudioNode;
  getState(): Promise<unknown>;
  setState(state: unknown): Promise<void>;
  getParameterInfo(...parameterIds: string[]): Promise<unknown>;
  /**
   * Present when the underlying WebAudioModule ships a GUI. Returns a fresh
   * GUI element the host mounts anywhere; release it with `destroyGui`. The
   * GUI lifecycle is independent of the audio lifecycle — destroying a GUI
   * never stops audio processing.
   */
  createGui?: () => Promise<HTMLElement>;
  /** Present when the underlying WebAudioModule exposes destroyGui. */
  destroyGui?: (gui: HTMLElement) => void;
  /** Tears down the plugin's AudioWorklet. Safe to call more than once. */
  destroy(): void;
}

export interface CreateWamInstanceOptions {
  initialState?: unknown;
  importFn?: WamModuleImport;
}

const defaultImport: WamModuleImport = (url) => import(/* @vite-ignore */ url);

let factoryCache = new Map<string, Promise<WamFactory>>();

/**
 * Load a WAM plugin module and resolve its factory (default export).
 * Cached per URL with a shared in-flight promise; failed loads are evicted
 * so a retry re-fetches instead of replaying the failure.
 */
export function loadWamFactory(
  url: string,
  importFn: WamModuleImport = defaultImport
): Promise<WamFactory> {
  const cached = factoryCache.get(url);
  if (cached) {
    return cached;
  }

  const pending = importFn(url)
    .then((mod) => {
      const candidate = (mod as { default?: unknown } | null | undefined)?.default;
      const isUsable =
        candidate !== null &&
        (typeof candidate === 'function' || typeof candidate === 'object') &&
        typeof (candidate as { createInstance?: unknown })?.createInstance === 'function';
      if (!isUsable) {
        throw new Error(
          PREFIX +
            'loadWamFactory: module at "' +
            url +
            '" has no usable default export. A WAM plugin module must default-export a WebAudioModule class with a static createInstance().'
        );
      }
      return candidate as WamFactory;
    })
    .catch((err: unknown) => {
      factoryCache.delete(url);
      throw err;
    });

  factoryCache.set(url, pending);
  return pending;
}

/**
 * Load (cached), instantiate, and validate a WAM plugin as an insert effect.
 * The descriptor is validated AFTER instantiation — many plugins only expose
 * it on the instance. Invalid plugins are destroyed before the error is thrown.
 */
export async function createWamInstance(
  url: string,
  audioContext: BaseAudioContext,
  hostGroupId: string,
  options: CreateWamInstanceOptions = {}
): Promise<WamPluginInstance> {
  const factory = await loadWamFactory(url, options.importFn);
  return instantiateAndWrap(factory, audioContext, hostGroupId, {
    initialState: options.initialState,
    label: url,
    url,
  });
}

export interface CreateWamInstanceFromFactoryOptions {
  initialState?: unknown;
  /** Names the plugin in validation/cleanup errors (no URL exists here). */
  label?: string;
}

/**
 * Instantiate and validate a WAM plugin from an already-obtained factory —
 * e.g. a WebAudioModule class generated by an in-browser Faust compile
 * (@dawcore/faust) — sharing createWamInstance's validate/wrap logic. The
 * resulting instance has no `url` and therefore cannot be cloned via
 * cloneInstanceInto; re-create it from its original source instead.
 */
export async function createWamInstanceFromFactory(
  factory: WamFactory,
  audioContext: BaseAudioContext,
  hostGroupId: string,
  options: CreateWamInstanceFromFactoryOptions = {}
): Promise<WamPluginInstance> {
  return instantiateAndWrap(factory, audioContext, hostGroupId, {
    initialState: options.initialState,
    label: options.label ?? 'factory-created plugin',
  });
}

/** Shared by createWamInstance / createWamInstanceFromFactory: instantiate,
 *  validate AFTER instantiation, apply initial state, wrap. Validation or
 *  state failure destroys the instance before the error is thrown. */
async function instantiateAndWrap(
  factory: WamFactory,
  audioContext: BaseAudioContext,
  hostGroupId: string,
  opts: { initialState?: unknown; label: string; url?: string }
): Promise<WamPluginInstance> {
  const wam = await factory.createInstance(hostGroupId, audioContext);

  try {
    validateEffectDescriptor(wam.descriptor, opts.label);
    if (opts.initialState !== undefined) {
      await wam.audioNode.setState(opts.initialState);
    }
  } catch (err) {
    try {
      wam.audioNode.destroy();
    } catch (destroyErr) {
      // Never let teardown failure mask the original validation/state error.
      console.warn(
        PREFIX +
          'createWamInstance: cleanup after failure also failed for "' +
          opts.label +
          '": ' +
          String(destroyErr)
      );
    }
    throw err;
  }

  let destroyed = false;
  return {
    ...(opts.url !== undefined ? { url: opts.url } : {}),
    descriptor: wam.descriptor,
    audioNode: wam.audioNode,
    getState: () => wam.audioNode.getState(),
    setState: (state: unknown) => wam.audioNode.setState(state),
    getParameterInfo: (...parameterIds: string[]) =>
      wam.audioNode.getParameterInfo(...parameterIds),
    ...(typeof wam.createGui === 'function' ? { createGui: () => wam.createGui!() } : {}),
    ...(typeof wam.destroyGui === 'function'
      ? { destroyGui: (gui: HTMLElement) => wam.destroyGui!(gui) }
      : {}),
    destroy: () => {
      if (destroyed) return;
      destroyed = true;
      wam.audioNode.destroy();
    },
  };
}

function validateEffectDescriptor(
  descriptor: WamPluginDescriptor | undefined,
  label: string
): void {
  const apiVersion = descriptor?.apiVersion;
  if (descriptor === undefined || typeof apiVersion !== 'string' || !apiVersion.startsWith('2.')) {
    throw new Error(
      PREFIX +
        'createWamInstance: plugin "' +
        label +
        '" has a missing or incompatible descriptor apiVersion ("' +
        String(apiVersion) +
        '"). This host supports WAM 2.x.'
    );
  }
  if (!descriptor.hasAudioInput) {
    throw new Error(
      PREFIX +
        'createWamInstance: plugin "' +
        label +
        '" has no audio input (hasAudioInput=false). Instrument-only plugins cannot be inserted into an effects chain.'
    );
  }
  if (!descriptor.hasAudioOutput) {
    throw new Error(
      PREFIX +
        'createWamInstance: plugin "' +
        label +
        '" has no audio output (hasAudioOutput=false) and cannot be inserted into an effects chain.'
    );
  }
}

/**
 * Re-create a live plugin on another context (typically an
 * OfflineAudioContext for export rendering) with the live instance's state.
 * WAM nodes are AudioWorklets bound to one context — they cannot be moved,
 * only cloned via getState/setState (the wam-studio cloneInto pattern).
 * The factory comes from the URL cache, so no re-fetch occurs.
 */
export async function cloneInstanceInto(
  instance: WamPluginInstance,
  targetContext: BaseAudioContext,
  hostGroupId: string,
  options: { importFn?: WamModuleImport } = {}
): Promise<WamPluginInstance> {
  if (instance.url === undefined) {
    throw new Error(
      PREFIX +
        'cloneInstanceInto: instance "' +
        instance.descriptor.name +
        '" has no source URL (factory-created, e.g. an in-browser Faust compile) — re-create it from its original source on the target context instead.'
    );
  }
  const state = await instance.getState();
  return createWamInstance(instance.url, targetContext, hostGroupId, {
    initialState: state,
    importFn: options.importFn,
  });
}

/** Test-only: drop all cached factory loads. */
export function _resetWamFactoryCacheForTests(): void {
  factoryCache = new Map();
}
